### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by quintonv** [matt-goldman/MauiCleanTodos#3]
Thanks for sharing the repo and creating the YouTube video. It helped a lot!

Would be great if you could update to .Net 8 and also the latest version of CleanArchitecture. The current one you are using still uses Duende where the latest apparently replaced that requirement.

**Comment by matt-goldman** [comment]
Thanks, I'm glad you found it helpful!

I'm presenting that talk again at NDC Sydney in January, so I'm planning to update it to .NET 8 for that. I haven't decided yet which CA template I'll update it to, I may use Jason's current template, but I might also use https://github.com/SSWConsulting/SSW.CleanArchitecture

**Comment by quintonv** [comment]
Sounds great, looking forward to watching the recording of the event!
Thanks again for the repo, it really helps

**Comment by quintonv** [comment]
Sounds great, looking forward to watching the recording of the event!
Thanks again for the repo, it really helps

**Comment by quintonv** [comment]
Happy new year Matt, hope you are doing well and that you're going to have an incredible 2024!

Do you know if the NDC Sydney event will be recorded and shared at a later stage? I would really like to watch the recording once it's available. South Africa is a bit far from Sydney to attend in person haha. Also looking forward to the MAUI 8 version update.

**Comment by matt-goldman** [comment]
I think so! I'm pretty sure all sessions are recorded and published on YouTube, they have been in previous years. And you never know maybe I'll get the chance to present somewhere closer to home for you one day.

**Comment by quintonv** [comment]
Thanks so much and that will be amazing!
